/* automatically generated by rust-bindgen 0.72.0 */

#![allow(unused)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

pub const BEATRICE_IN_HOP_LENGTH: u32 = 160;
pub const BEATRICE_OUT_HOP_LENGTH: u32 = 240;
pub const BEATRICE_PITCH_BINS_PER_OCTAVE: u32 = 96;
pub const BEATRICE_WAVEFORM_GENERATOR_HIDDEN_CHANNELS: u32 = 256;
pub const BEATRICE_IN_SAMPLE_RATE: u32 = 16000;
pub const BEATRICE_OUT_SAMPLE_RATE: u32 = 24000;
pub const BEATRICE_20A2_PHONE_CHANNELS: u32 = 256;
pub const BEATRICE_20A2_PITCH_BINS: u32 = 384;
pub const BEATRICE_20B1_PHONE_CHANNELS: u32 = 256;
pub const BEATRICE_20B1_PITCH_BINS: u32 = 384;
pub const BEATRICE_20RC0_PHONE_CHANNELS: u32 = 128;
pub const BEATRICE_20RC0_PITCH_BINS: u32 = 448;
pub const BEATRICE_20RC0_CODEBOOK_SIZE: u32 = 512;
pub const BEATRICE_20RC0_KV_LENGTH: u32 = 384;
pub const BEATRICE_20RC0_KV_SPEAKER_EMBEDDING_CHANNELS: u32 = 128;
pub const BEATRICE_20RC0_N_BLOCKS: u32 = 4;
pub const Beatrice_ErrorCode_Beatrice_kSuccess: Beatrice_ErrorCode = 0;
pub const Beatrice_ErrorCode_Beatrice_kFileOpenError: Beatrice_ErrorCode = 1;
pub const Beatrice_ErrorCode_Beatrice_kFileTooSmall: Beatrice_ErrorCode = 2;
pub const Beatrice_ErrorCode_Beatrice_kFileTooLarge: Beatrice_ErrorCode = 3;
pub const Beatrice_ErrorCode_Beatrice_kInvalidFileSize: Beatrice_ErrorCode = 4;
pub type Beatrice_ErrorCode = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Beatrice20a2_PhoneExtractor {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Beatrice20a2_PhoneContext1 {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Beatrice20a2_PitchEstimator {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Beatrice20a2_PitchContext1 {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Beatrice20a2_WaveformGenerator {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Beatrice20a2_WaveformContext1 {
    _unused: [u8; 0],
}

#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20a2_CreatePhoneExtractor() -> *mut Beatrice20a2_PhoneExtractor;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20a2_DestroyPhoneExtractor(phone_extractor: *mut Beatrice20a2_PhoneExtractor);
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20a2_CreatePhoneContext1() -> *mut Beatrice20a2_PhoneContext1;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20a2_DestroyPhoneContext1(ctx: *mut Beatrice20a2_PhoneContext1);
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20a2_ReadPhoneExtractorParameters(
        phone_extractor: *mut Beatrice20a2_PhoneExtractor,
        filename: *const ::std::os::raw::c_char,
    ) -> Beatrice_ErrorCode;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20a2_ExtractPhone1(
        phone_extractor: *const Beatrice20a2_PhoneExtractor,
        input: *const f32,
        output: *mut f32,
        ctx: *mut Beatrice20a2_PhoneContext1,
    );
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20a2_CreatePitchEstimator() -> *mut Beatrice20a2_PitchEstimator;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20a2_DestroyPitchEstimator(pitch_estimator: *mut Beatrice20a2_PitchEstimator);
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20a2_CreatePitchContext1() -> *mut Beatrice20a2_PitchContext1;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20a2_DestroyPitchContext1(ctx: *mut Beatrice20a2_PitchContext1);
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20a2_ReadPitchEstimatorParameters(
        pitch_estimator: *mut Beatrice20a2_PitchEstimator,
        filename: *const ::std::os::raw::c_char,
    ) -> Beatrice_ErrorCode;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20a2_SetMinQuantizedPitch(
        ctx: *mut Beatrice20a2_PitchContext1,
        min_quantized_pitch: ::std::os::raw::c_int,
    );
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20a2_SetMaxQuantizedPitch(
        ctx: *mut Beatrice20a2_PitchContext1,
        max_quantized_pitch: ::std::os::raw::c_int,
    );
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20a2_EstimatePitch1(
        pitch_estimator: *const Beatrice20a2_PitchEstimator,
        input: *const f32,
        output_quantized_pitch: *mut ::std::os::raw::c_int,
        output_pitch_feature: *mut f32,
        ctx: *mut Beatrice20a2_PitchContext1,
    );
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20a2_ReadNSpeakers(
        filename: *const ::std::os::raw::c_char,
        output: *mut ::std::os::raw::c_int,
    ) -> Beatrice_ErrorCode;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20a2_ReadSpeakerEmbeddings(
        filename: *const ::std::os::raw::c_char,
        output: *mut f32,
    ) -> Beatrice_ErrorCode;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20a2_CreateWaveformGenerator() -> *mut Beatrice20a2_WaveformGenerator;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20a2_DestroyWaveformGenerator(
        waveform_generator: *mut Beatrice20a2_WaveformGenerator,
    );
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20a2_CreateWaveformContext1() -> *mut Beatrice20a2_WaveformContext1;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20a2_DestroyWaveformContext1(ctx: *mut Beatrice20a2_WaveformContext1);
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20a2_ReadWaveformGeneratorParameters(
        waveform_generator: *mut Beatrice20a2_WaveformGenerator,
        filename: *const ::std::os::raw::c_char,
    ) -> Beatrice_ErrorCode;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20a2_GenerateWaveform1(
        waveform_generator: *const Beatrice20a2_WaveformGenerator,
        input_phone: *const f32,
        input_quantized_pitch: *const ::std::os::raw::c_int,
        input_pitch_features: *const f32,
        input_speaker_embedding: *const f32,
        output: *mut f32,
        ctx: *mut Beatrice20a2_WaveformContext1,
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Beatrice20b1_PhoneExtractor {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Beatrice20b1_PhoneContext1 {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Beatrice20b1_PitchEstimator {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Beatrice20b1_PitchContext1 {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Beatrice20b1_WaveformGenerator {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Beatrice20b1_WaveformContext1 {
    _unused: [u8; 0],
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20b1_CreatePhoneExtractor() -> *mut Beatrice20b1_PhoneExtractor;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20b1_DestroyPhoneExtractor(phone_extractor: *mut Beatrice20b1_PhoneExtractor);
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20b1_CreatePhoneContext1() -> *mut Beatrice20b1_PhoneContext1;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20b1_DestroyPhoneContext1(ctx: *mut Beatrice20b1_PhoneContext1);
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20b1_ReadPhoneExtractorParameters(
        phone_extractor: *mut Beatrice20b1_PhoneExtractor,
        filename: *const ::std::os::raw::c_char,
    ) -> Beatrice_ErrorCode;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20b1_ExtractPhone1(
        phone_extractor: *const Beatrice20b1_PhoneExtractor,
        input: *const f32,
        output: *mut f32,
        ctx: *mut Beatrice20b1_PhoneContext1,
    );
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20b1_CreatePitchEstimator() -> *mut Beatrice20b1_PitchEstimator;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20b1_DestroyPitchEstimator(pitch_estimator: *mut Beatrice20b1_PitchEstimator);
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20b1_CreatePitchContext1() -> *mut Beatrice20b1_PitchContext1;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20b1_DestroyPitchContext1(ctx: *mut Beatrice20b1_PitchContext1);
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20b1_ReadPitchEstimatorParameters(
        pitch_estimator: *mut Beatrice20b1_PitchEstimator,
        filename: *const ::std::os::raw::c_char,
    ) -> Beatrice_ErrorCode;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20b1_SetMinQuantizedPitch(
        ctx: *mut Beatrice20b1_PitchContext1,
        min_quantized_pitch: ::std::os::raw::c_int,
    );
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20b1_SetMaxQuantizedPitch(
        ctx: *mut Beatrice20b1_PitchContext1,
        max_quantized_pitch: ::std::os::raw::c_int,
    );
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20b1_EstimatePitch1(
        pitch_estimator: *const Beatrice20b1_PitchEstimator,
        input: *const f32,
        output_quantized_pitch: *mut ::std::os::raw::c_int,
        output_pitch_feature: *mut f32,
        ctx: *mut Beatrice20b1_PitchContext1,
    );
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20b1_ReadNSpeakers(
        filename: *const ::std::os::raw::c_char,
        output: *mut ::std::os::raw::c_int,
    ) -> Beatrice_ErrorCode;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20b1_ReadSpeakerEmbeddings(
        filename: *const ::std::os::raw::c_char,
        output: *mut f32,
    ) -> Beatrice_ErrorCode;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20b1_CreateWaveformGenerator() -> *mut Beatrice20b1_WaveformGenerator;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20b1_DestroyWaveformGenerator(
        waveform_generator: *mut Beatrice20b1_WaveformGenerator,
    );
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20b1_CreateWaveformContext1() -> *mut Beatrice20b1_WaveformContext1;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20b1_DestroyWaveformContext1(ctx: *mut Beatrice20b1_WaveformContext1);
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20b1_ReadWaveformGeneratorParameters(
        waveform_generator: *mut Beatrice20b1_WaveformGenerator,
        filename: *const ::std::os::raw::c_char,
    ) -> Beatrice_ErrorCode;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20b1_GenerateWaveform1(
        waveform_generator: *const Beatrice20b1_WaveformGenerator,
        input_phone: *const f32,
        input_quantized_pitch: *const ::std::os::raw::c_int,
        input_pitch_features: *const f32,
        input_speaker_embedding: *const f32,
        output: *mut f32,
        ctx: *mut Beatrice20b1_WaveformContext1,
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Beatrice20rc0_PhoneExtractor {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Beatrice20rc0_PhoneContext1 {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Beatrice20rc0_PitchEstimator {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Beatrice20rc0_PitchContext1 {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Beatrice20rc0_WaveformGenerator {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Beatrice20rc0_WaveformContext1 {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Beatrice20rc0_EmbeddingSetter {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Beatrice20rc0_EmbeddingContext {
    _unused: [u8; 0],
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_CreatePhoneExtractor() -> *mut Beatrice20rc0_PhoneExtractor;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_DestroyPhoneExtractor(phone_extractor: *mut Beatrice20rc0_PhoneExtractor);
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_CreatePhoneContext1() -> *mut Beatrice20rc0_PhoneContext1;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_DestroyPhoneContext1(ctx: *mut Beatrice20rc0_PhoneContext1);
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_ReadPhoneExtractorParameters(
        phone_extractor: *mut Beatrice20rc0_PhoneExtractor,
        filename: *const ::std::os::raw::c_char,
    ) -> Beatrice_ErrorCode;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_SetVQNumNeighbors(
        ctx: *mut Beatrice20rc0_PhoneContext1,
        num_neighbors: ::std::os::raw::c_int,
    );
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_ExtractPhone1(
        phone_extractor: *const Beatrice20rc0_PhoneExtractor,
        input: *const f32,
        output: *mut f32,
        ctx: *mut Beatrice20rc0_PhoneContext1,
    );
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_CreatePitchEstimator() -> *mut Beatrice20rc0_PitchEstimator;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_DestroyPitchEstimator(pitch_estimator: *mut Beatrice20rc0_PitchEstimator);
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_CreatePitchContext1() -> *mut Beatrice20rc0_PitchContext1;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_DestroyPitchContext1(ctx: *mut Beatrice20rc0_PitchContext1);
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_ReadPitchEstimatorParameters(
        pitch_estimator: *mut Beatrice20rc0_PitchEstimator,
        filename: *const ::std::os::raw::c_char,
    ) -> Beatrice_ErrorCode;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_SetMinQuantizedPitch(
        ctx: *mut Beatrice20rc0_PitchContext1,
        min_quantized_pitch: ::std::os::raw::c_int,
    );
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_SetMaxQuantizedPitch(
        ctx: *mut Beatrice20rc0_PitchContext1,
        max_quantized_pitch: ::std::os::raw::c_int,
    );
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_EstimatePitch1(
        pitch_estimator: *const Beatrice20rc0_PitchEstimator,
        input: *const f32,
        output_quantized_pitch: *mut ::std::os::raw::c_int,
        output_pitch_feature: *mut f32,
        ctx: *mut Beatrice20rc0_PitchContext1,
    );
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_ReadNSpeakers(
        filename: *const ::std::os::raw::c_char,
        output: *mut ::std::os::raw::c_int,
    ) -> Beatrice_ErrorCode;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_ReadSpeakerEmbeddings(
        filename: *const ::std::os::raw::c_char,
        output_codebook: *mut f32,
        output_additive_speaker_embedding: *mut f32,
        output_formant_shift_embedding: *mut f32,
        output_key_value_speaker_embedding: *mut f32,
    ) -> Beatrice_ErrorCode;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_CreateWaveformGenerator() -> *mut Beatrice20rc0_WaveformGenerator;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_DestroyWaveformGenerator(
        waveform_generator: *mut Beatrice20rc0_WaveformGenerator,
    );
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_CreateWaveformContext1() -> *mut Beatrice20rc0_WaveformContext1;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_DestroyWaveformContext1(ctx: *mut Beatrice20rc0_WaveformContext1);
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_ReadWaveformGeneratorParameters(
        waveform_generator: *mut Beatrice20rc0_WaveformGenerator,
        filename: *const ::std::os::raw::c_char,
    ) -> Beatrice_ErrorCode;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_GenerateWaveform1(
        waveform_generator: *const Beatrice20rc0_WaveformGenerator,
        input_phone: *const f32,
        input_quantized_pitch: *const ::std::os::raw::c_int,
        input_pitch_features: *const f32,
        output: *mut f32,
        ctx: *mut Beatrice20rc0_WaveformContext1,
    );
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_CreateEmbeddingSetter() -> *mut Beatrice20rc0_EmbeddingSetter;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_DestroyEmbeddingSetter(
        embedding_setter: *mut Beatrice20rc0_EmbeddingSetter,
    );
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_CreateEmbeddingContext() -> *mut Beatrice20rc0_EmbeddingContext;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_DestroyEmbeddingContext(ctx: *mut Beatrice20rc0_EmbeddingContext);
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_ReadEmbeddingSetterParameters(
        embedding_setter: *mut Beatrice20rc0_EmbeddingSetter,
        filename: *const ::std::os::raw::c_char,
    ) -> Beatrice_ErrorCode;
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_SetCodebook(
        phone_ctx: *mut Beatrice20rc0_PhoneContext1,
        codebook: *const f32,
    );
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_SetAdditiveSpeakerEmbedding(
        embedding_setter: *const Beatrice20rc0_EmbeddingSetter,
        embedding: *const f32,
        embedding_ctx: *mut Beatrice20rc0_EmbeddingContext,
        waveform_ctx: *mut Beatrice20rc0_WaveformContext1,
    );
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_SetFormantShiftEmbedding(
        embedding_setter: *const Beatrice20rc0_EmbeddingSetter,
        embedding: *const f32,
        embedding_ctx: *mut Beatrice20rc0_EmbeddingContext,
        waveform_ctx: *mut Beatrice20rc0_WaveformContext1,
    );
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_RegisterKeyValueSpeakerEmbedding(
        embedding_setter: *const Beatrice20rc0_EmbeddingSetter,
        kv_speaker_embedding: *const f32,
        embedding_ctx: *mut Beatrice20rc0_EmbeddingContext,
    );
}
#[link(name = "beatrice", kind = "static")]
unsafe extern "C" {
    pub fn Beatrice20rc0_SetKeyValueSpeakerEmbedding(
        embedding_setter: *const Beatrice20rc0_EmbeddingSetter,
        block: ::std::os::raw::c_int,
        embedding_ctx: *mut Beatrice20rc0_EmbeddingContext,
        waveform_ctx: *mut Beatrice20rc0_WaveformContext1,
    );
}
